# Synchronize this repository with the project wiki 
name: sync-wiki
on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-wikis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # PAT with repo & workflow permission
          token: ${{ secrets.EVIDENT_WIKI_SYNC }}
          fetch-depth: 0
      - name: Add wiki repo and push changes
        # Note: `master` is the default branch for GitHub wikis
        run: |
          git config --global user.email "wikibot@blumafe.com"
          git config --global user.name "Wiki Template Bot"
          git remote add upstream https://github.com/mhatzl/evident.wiki.git
          git fetch upstream
          git merge --allow-unrelated-histories --strategy-option=ours upstream/master
          git push --force upstream main:master
